export const BALANCE = {
  world: {
    width: 36,
    depth: 24,
  },
  player: {
    radius: 0.42,
    height: 1.72,
    moveSpeed: 4.2,
    dodgeSpeed: 9.2,
    dodgeDurationSeconds: 0.2,
    dodgeCooldownSeconds: 0.95,
    attackDurationSeconds: 0.22,
    attackCooldownSeconds: 0.32,
    maxHealth: 5,
    parryWindowSeconds: 0.18,
    spawn: { x: 4.5, z: 12 },
    attackReach: 1.8,
    attackArcDeg: 55,
    damageCooldownSeconds: 1,
    knockbackDistance: 2.3,
  },
  camera: {
    distance: 2.35,
    shoulderOffset: 0.42,
    height: 1.68,
    minDistance: 0.78,
  },
  guard: {
    radius: 0.42,
    patrolSpeed: 2.1,
    suspiciousSpeed: 2.7,
    chaseSpeed: 3.7,
    returnSpeed: 2.4,
    sightDistance: 8.5,
    sightDistanceTorch: 13.5,
    chaseDistance: 5.5,
    nearDetection: 1.8,
    fovDeg: 82,
    stunSeconds: 3.2,
    navStep: 0.5,
    suspiciousDurationSeconds: 1.8,
    chaseMemorySeconds: 1.2,
    spawn: { x: 28.2, z: 16.1 },
    patrolPoints: [
      { x: 28.2, z: 16.1 },
      { x: 23.6, z: 16.1 },
      { x: 23.6, z: 11.5 },
      { x: 28.2, z: 11.5 },
    ],
  },
  torch: {
    pickup: { x: 8.9, y: 0.58, z: 16.95 },
    interactDistance: 1.5,
    onIntensity: 2.8,
    offIntensity: 0.85,
    onDistance: 21,
    offDistance: 11,
    fillIntensityOn: 0.45,
    fillIntensityOff: 0.95,
    fillDistanceOn: 3.8,
    fillDistanceOff: 5.8,
    keyLightIntensityOn: 1.1,
    keyLightIntensityOff: 1.5,
    countdownDrainMultiplier: 1.65,
    guardExposureMultiplier: 1.35,
  },
  countdown: {
    startSeconds: 75,
    lowWarningSeconds: 20,
    criticalWarningSeconds: 10,
  },
  hound: {
    spawn: { x: 31.4, z: 4.1 },
    releaseInvestigateTarget: { x: 26.3, z: 7.1 },
    releasedSpeed: 3.3,
    searchSpeed: 4.1,
    chaseSpeed: 5.4,
    resetSpeed: 4.3,
    sightDistance: 12.8,
    nearDetection: 2.9,
    fovDeg: 112,
    maxHealth: 2,
    attackRange: 1.15,
    attackDurationSeconds: 0.38,
    attackCooldownSeconds: 0.9,
    damage: 2,
    damageCooldownSeconds: 1.2,
    searchDurationSeconds: 2.2,
    chaseMemorySeconds: 1.4,
    recoverSeconds: 2.6,
    resetTolerance: 0.55,
    warningSeconds: 2.6,
    warningLightRadius: 3.8,
    warningLightIntensity: 1.6,
  },
  ui: {
    messageDurationSeconds: 3.1,
  },
  audio: {
    guardFootstepIntervalSeconds: 0.48,
    houndGrowlIntervalSeconds: 0.9,
    barkCooldownSeconds: 1.1,
  },
} as const;
